# Generated by Django 3.0.5 on 2020-05-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0007_auto_20200501_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='answers',
            field=models.IntegerField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
