# Generated by Django 3.0.5 on 2020-05-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0009_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'managed': True, 'verbose_name': 'questions', 'verbose_name_plural': 'questionss'},
        ),
    ]
