# Generated by Django 3.0.5 on 2020-05-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0010_auto_20200501_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='inputs',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(max_length=1000),
        ),
    ]
