# Generated by Django 3.0.5 on 2020-05-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0012_auto_20200501_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='answered',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
    ]
