# Generated by Django 3.0.5 on 2020-05-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0015_auto_20200501_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='no',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
