# Generated by Django 3.0.5 on 2020-05-01 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0016_auto_20200501_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='images/')),
                ('cat', models.CharField(max_length=150)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='register',
            name='answers',
            field=models.IntegerField(),
        ),
    ]
