# Generated by Django 3.0.5 on 2020-05-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0017_auto_20200501_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=300)),
                ('lname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('comments', models.TextField()),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
