# Generated by Django 3.0.6 on 2020-06-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0019_auto_20200601_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='answer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
