# Generated by Django 3.0.6 on 2020-06-01 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compiler', '0021_auto_20200601_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='completed',
            field=models.ManyToManyField(related_name='completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
