# Generated by Django 3.0.6 on 2020-06-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0023_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='reult',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
