# Generated by Django 3.0.6 on 2020-06-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0024_quizes_reult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
