# Generated by Django 3.0.6 on 2020-06-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0027_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='qid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
