# Generated by Django 3.0.6 on 2020-06-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0029_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='end',
            field=models.BooleanField(default=False),
        ),
    ]
