# Generated by Django 3.0.6 on 2020-06-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0030_quizes_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
